version: 1

name: ym-saholman-com

pipelines:
  dev:
    phases:
    - type: github
      name: Github
      owner: saholman
      repo: ym.saholman.com
      branch: master
    - type: codebuild
      name: Build
      build_image: aws/codebuild/eb-nodejs-6.10.0-amazonlinux-64:4.0.0
    - type: handel
      name: DevDeploy
      environments_to_deploy:
      - dev
# https://handel-codepipeline.readthedocs.io
